seed: 1

type: train_nerf_highres

training:
  num_epochs: 250
  batch_size: 1024
  lr: 0.0005

  lr_scheduler_step_size: 10
  lr_scheduler_gamma: 0.8

  checkpoint_path: ./checkpoints_res
  checkpoint_interval: 5
  resume: False

  render_interval: 10

data:
  image_size: [512, 512]
  dataset_name: lego

renderer:
  type: volume
  # chunk_size: 32768
  chunk_size: 3600
  white_background: True

sampler:
  type: stratified
  n_pts_per_ray: 512

  min_depth: 2.0
  max_depth: 6.0

implicit_function:
  type: nerf

  n_harmonic_functions_xyz: 6
  n_harmonic_functions_dir: 2
  n_hidden_neurons_xyz: 128
  n_hidden_neurons_dir: 64
  density_noise_std: 0.0
  n_layers_xyz: 6
  append_xyz: [3]



